# Generated by Django 5.1.4 on 2025-01-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_rate', models.FloatField(blank=True, null=True)),
                ('control', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('stabbr', models.CharField(blank=True, max_length=256, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('home_page', models.CharField(blank=True, max_length=256, null=True)),
                ('num_studs', models.IntegerField(blank=True, null=True)),
                ('satvr25', models.IntegerField(blank=True, null=True)),
                ('satvr50', models.IntegerField(blank=True, null=True)),
                ('satvr75', models.IntegerField(blank=True, null=True)),
                ('satmt25', models.IntegerField(blank=True, null=True)),
                ('satmt50', models.IntegerField(blank=True, null=True)),
                ('satmt75', models.IntegerField(blank=True, null=True)),
                ('tuition_fee_in', models.FloatField(blank=True, null=True)),
                ('tuition_fee_out', models.FloatField(blank=True, null=True)),
                ('np_curl', models.FloatField(blank=True, null=True)),
                ('men', models.IntegerField(blank=True, null=True)),
                ('women', models.IntegerField(blank=True, null=True)),
                ('white', models.IntegerField(blank=True, null=True)),
                ('black', models.IntegerField(blank=True, null=True)),
                ('hispanic', models.IntegerField(blank=True, null=True)),
                ('asian', models.IntegerField(blank=True, null=True)),
                ('ai_an', models.IntegerField(blank=True, null=True)),
                ('na_pi', models.IntegerField(blank=True, null=True)),
                ('two', models.IntegerField(blank=True, null=True)),
                ('alien', models.IntegerField(blank=True, null=True)),
                ('unknown', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
