# Generated by Django 5.1.4 on 2025-01-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_institution_num_studs_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='ai_an',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='alien',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='asian',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='black',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='hispanic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='men',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='na_pi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='np_curl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='two',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='unknown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='white',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='women',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
