# Generated by Django 5.1.4 on 2025-01-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_institution_ai_an_alter_institution_alien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='zip_code',
        ),
    ]
